Update CONTRIBUTING.md
jupyter/notebook pull request #7473
Opened 2024-10-03 16:58 UTC by hackit-coder

Updated the filed with typos and correct grammar

2024-10-04 14:15 UTC, hackit-coder commented
Hello anyone there

2024-10-04 14:27 UTC, krassowski requested changes
If you are human, thank you for contributing. Please appreciate that PRs reviews are often done in free time of volunteers and there is no need to ping back after just 24 hours.

On the PR itself, I am not convinced on most of these suggestions.

2024-10-04 14:27 UTC, krassowski commented on CONTRIBUTING.md
> +Thanks for showing interest on contributing to Jupyter Notebook!
This sounds like bad grammar to me, there is only one result on Google for "Thanks for showing interest on contributing to".

2024-10-04 14:27 UTC, krassowski commented on CONTRIBUTING.md
> +The developmental installations described above fetches JavaScript dependencies from [npmjs](https://www.npmjs.com/),
Both "developmental" and "installations" sound incorrect in this context.

2024-10-04 14:27 UTC, krassowski commented on CONTRIBUTING.md
> +Which should run any autoformatting on your code
This is continuation of previous sentence so was right to my eye

2024-10-04 14:27 UTC, krassowski commented on CONTRIBUTING.md
> +    The easiest way is to do it is manually move the new entry in _package.json_ from _dependencies_ to _resolutions_.
The existing text sounds fine to me.

2026-04-23 14:47 UTC, jtpio commented
Closing as mostly invalid.

Thanks @krassowski for taking the time to comment.

2026-04-23 14:47 UTC, closed without merging