Update README.md
jupyter/notebook pull request #7474
Opened 2024-10-03 17:10 UTC by hackit-coder

Steps to host Jpyter as web interface on Google, Mozilla etc.

2024-10-04 04:49 UTC, hackit-coder commented
Hello anyone there

2024-10-04 14:31 UTC, krassowski requested changes
These instructions are incorrect for a number of reasons:
- the port 8888 may be taken and a different port would be used instead
- usually there is no need to open a browser - the command above will open the default browser
- `localhost` may not work on specific systems and instead using 127.0.0.1 may be needed
- the URL above will not include the token needed to login and this token will be different each time

Each PR should address an issue. This PR is not linked to any issue. In future I would encourage you to:
- open an issue first to discuss potential enhancements
- if you are looking for a way to contribute, looking through the issues and picking up something tagged as good first issue :)

2024-10-05 04:11 UTC, hackit-coder commented
Ok changed it a bit

2024-10-09 14:32 UTC, hackit-coder commented
@krassowski can you check

2024-10-09 16:13 UTC, krassowski reviewed
I am still not convinced that this is an improvement over status quo. These instructions can be still misleading and usually none of these steps are necessary as a browser with the auto-generated temporary redirect file (which is also safer than typing in a token) will automatically open.

Maybe describing what would typically happen (that browser would open etc) and that if it does not then user should open and copy-paste URL could be more useful?

2024-10-09 16:13 UTC, krassowski commented on README.md
> +3. Press Enter.
`baralong`?

2024-10-16 16:13 UTC, hackit-coder commented
Updated it in the previous commit, it' bar along not baralong my bad!

2026-04-24 05:51 UTC, jtpio commented
Closing as stale.

2026-04-24 05:51 UTC, closed without merging